#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  echo "Usage: junos_route vpn_gateway your_gateway device"
  exit 1
fi

sudo ip r add default via "$2" dev "$3" proto static metric 0
sudo ip route add 10.0.0.0/8 via "$1" metric 450
sudo ip route add 172.16.0.0/12 via "$1" metric 450
sudo ip route add 192.168.0.0/16 via "$1" metric 450
